name = "CircuitAnalysis"
uuid = "1e01fd38-ae70-11e9-267a-1dc6a35ae3d5"
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
